# std_msgs/Header
std_msgs/Header header

# For HMG IONIQ
float64 cluster_odometer

float64 lateral_accel
float64 longitudinal_accel
float64 yaw_rate

float64 steering_wheel_angle
float64 steering_tire_angle
float64 steering_speed
float64 steering_torque
uint8   steering_state

float64 wheel_velocity_fl
float64 wheel_velocity_fr
float64 wheel_velocity_rl
float64 wheel_velocity_rr
float64 wheel_velocity_f_avg
float64 wheel_velocity_r_avg
float64 wheel_velocity_avg

float64 motor_torque_f
float64 motor_torque_r

float64 accel_position
float64 brake_pressure
uint8 brake_active
uint8 gear_select

uint8 operation_mode
uint8 lateral_autonomous_mode
uint8 longitudinal_autonomous_mode
