std_msgs/Bool  has_objects 
Objects        objects 

std_msgs/Bool  has_attention_objects 
Objects        attention_objects 

std_msgs/Bool  has_freespace 
FreeSpaceInfos freespace_infos 

std_msgs/Bool   has_lanes 
Lanes           lanes 

std_msgs/Bool   has_curbs 
Curbs           curbs 

std_msgs/Bool   has_non_ground_indices 
Indices         non_ground_indices 

std_msgs/Bool   has_ground_indices 
Indices         ground_indices

std_msgs/Bool   has_background_indices 
Indices         background_indices 

# std_msgs/Bool   has_attention_indices 
# Indices         attention_indices 