Point3f[] polygon
Point3f[] reference

std_msgs/Int32[]    cloud_indices
std_msgs/Int32[]    attention_indices 
std_msgs/Float32[]  latent_types
std_msgs/Int32    size_type 
std_msgs/Int32    mode 
std_msgs/Bool    in_roi 
Matrix3f         angle_velocity_cov 
Point3f          angle_acceleration 
Matrix3f         angle_acceleration_cov 

Point3f[]           trajectory 
Point3f[]           history_velocity
std_msgs/Int32[]    history_type 
Point3d             gps_info 
