float64 latitude                  # GCS Coordinates latitude
float64 longitude                 # GCS Coordinates longitude
float64 elevation                 # GCS Coordinates elevation

float64 x
float64 y
float64 z

float32 roll                      # yaw in vehicle coordinates [rad]
float32 pitch                     # yaw in vehicle coordinates [rad]
float32 yaw                       # yaw in vehicle coordinates [rad]
float32 ego_roll                      # yaw in vehicle coordinates [rad]
float32 ego_pitch                     # yaw in vehicle coordinates [rad]
float32 ego_yaw                       # yaw in vehicle coordinates [rad]

float32 roll_rate                      # yaw in vehicle coordinates [rad]
float32 pitch_rate                     # yaw in vehicle coordinates [rad]
float32 yaw_rate                       # yaw in vehicle coordinates [rad]

float32 v_x                       # velocity in vehicle coordinates [m/s]
float32 v_y                       # velocity in vehicle coordinates [m/s]
float32 a_x                       # acceleration in vehicle coordinates [m/s^2]
float32 a_y                       # acceleration in vehicle coordinates [m/s^2]
