string message    # informational, e.g. name of triggering node
---
bool   success    # indicate successful run of triggered service
int32  cycletime  # default cycle time in ms 
string message    # informational, e.g. for error messages
